### PR TITLE
Update lai:collection-extensions to v0.3

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Updates lai:collection-extensions to the latest version for compatibility with Meteor 2.3+

Speaking of which @dburles are you interested in working on this or would you be interested in moving this to [Meteor Community Packages](https://github.com/Meteor-Community-Packages)?

https://github.com/Meteor-Community-Packages/organization/issues/59

### CODE REVIEW

**Comment by dburles** [comment]
Thanks @StorytellerCZ! I am happy to move this package over.

**Comment by dburles** [comment]
Published 0.3.6

**Comment by dburles** [comment]
I've just added `communitypackages` as maintainer. Ok to move the repo over also.

**Comment by StorytellerCZ** [comment]
@dburles I have invited you to Meteor Community Packages. Once you are a member I think you should be able to move the package over. I will then take it from there.

**Comment by dburles** [comment]
Great, thanks I've just transferred it across.

**Comment by StorytellerCZ** [comment]
@dburles Thank you! I have made the finishing touches.

**Pull request merged**
